import React from 'react';
import { RefreshCw, Shuffle } from 'lucide-react';
import { FIT_MODES } from '../fit/index.js';

const Toggle = ({ on, onToggle, labelOn, labelOff }) => (
  <button
    onClick={onToggle}
    className={`relative inline-flex h-5 w-9 items-center rounded-full transition-colors ${
      on ? 'bg-[var(--accent)]' : 'bg-[var(--border-strong)]'
    }`}
  >
    <span
      className={`inline-block h-3.5 w-3.5 transform rounded-full bg-white shadow transition-transform ${
        on ? 'translate-x-4' : 'translate-x-1'
      }`}
    />
    <span className="sr-only">{on ? labelOn : labelOff}</span>
  </button>
);

const FIT_MODE_ORDER = ['catmull', 'linear', 'steps', 'poly', 'cosine'];

const FIT_MODE_DESCRIPTIONS = {
  cosine: 'Fits a + b·cos(2π(ct+d)) per channel. Smooth, loops perfectly with locked freq. Best for organic gradients.',
  poly: 'Least-squares polynomial through the colors. Can overshoot — use clamp. Higher degree = more flexibility, more risk of artifacts.',
  linear: 'Direct mix() between color stops. Exact colors, no overshoot. Weight dominance stretches dominant colors across more t-range.',
  steps: 'Hard cuts between colors. Each color occupies t-range proportional to its area. Good for quantized / posterized looks.',
  catmull: 'Catmull-Rom spline through colors. Smooth like cosine but passes exactly through each color. Weight dominance adjusts stop spacing.',
};

const PaletteModeSettings = ({
  paletteMethod, setPaletteMethod,
  paletteFitMode, setPaletteFitMode,
  colorCount, setColorCount,
  lockFrequency, setLockFrequency,
  weightDominance, setWeightDominance,
  degree, setDegree,
  apiModel, setApiModel,
  apiModels,
  apiSeedCount, setApiSeedCount,
  extractedColors,
  paletteSwatchRef,
  paletteGradientRef,
  imageSrc,
  onRegenerate,
  onShuffle,
}) => (
  <div className="space-y-3">
    <h3 className="text-[10px] font-semibold text-[var(--text-muted)] uppercase tracking-widest">
      Palette Settings
    </h3>

    <div className="flex items-center gap-2">
      <span className="text-[9px] font-semibold text-[var(--text-muted)] uppercase tracking-widest">Extraction</span>
      <div className="flex-1 border-t border-[var(--border)]" />
    </div>

    <div className="flex bg-[var(--surface-muted)] p-0.5 rounded-sm">
      {['dominant', 'generative', 'api'].map((method) => (
        <button
          key={method}
          onClick={() => setPaletteMethod(method)}
          className={`flex-1 py-1.5 text-[10px] rounded-sm font-semibold tracking-widest uppercase transition-all ${
            paletteMethod === method
              ? 'bg-[var(--surface)] text-[var(--accent)]'
              : 'text-[var(--text-muted)] hover:text-[var(--text)]'
          }`}
        >
          {method === 'api' ? 'API' : method.charAt(0).toUpperCase() + method.slice(1)}
        </button>
      ))}
    </div>

    <div className="flex items-center justify-between">
      <p className="text-[10px] text-[var(--text-muted)] leading-relaxed">
        {paletteMethod === 'dominant' && 'Ranks colors by pixel coverage — most frequent colors first. Deterministic.'}
        {paletteMethod === 'generative' && 'Runs k-means 24× on random pixel subsets, picks the run with best color spread. Varies on regenerate.'}
        {paletteMethod === 'api' && `Colormind AI palette — ${apiSeedCount} color${apiSeedCount !== 1 ? 's' : ''} locked from image, ${5 - apiSeedCount} generated by AI. Always 5 colors. Varies on regenerate.`}
      </p>
      {(paletteMethod === 'generative' || paletteMethod === 'api') && imageSrc && (
        <button
          onClick={onRegenerate}
          className="flex items-center gap-1 text-[10px] bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-white px-2.5 py-1 rounded-sm ml-3 shrink-0 tracking-widest uppercase font-semibold transition-colors"
        >
          <RefreshCw className="w-3 h-3" /> Regenerate
        </button>
      )}
    </div>

    {paletteMethod === 'api' && (
      <>
        <div className="flex items-center gap-3">
          <label className="text-[10px] font-semibold text-[var(--text-secondary)] w-20 shrink-0 uppercase tracking-wider">Model</label>
          <select
            value={apiModel}
            onChange={(e) => setApiModel(e.target.value)}
            className="flex-1 text-xs bg-[var(--bg)] border border-[var(--border)] rounded-sm px-2 py-1 text-[var(--text)] cursor-pointer focus:outline-none focus:border-[var(--accent)]"
          >
            {apiModels.map((m) => <option key={m} value={m}>{m}</option>)}
          </select>
        </div>
        <div className="flex items-center gap-4">
          <label className="text-[10px] font-semibold text-[var(--text-secondary)] w-20 uppercase tracking-wider">Img seeds</label>
          <input
            type="range" min="1" max="4" step="1"
            value={apiSeedCount}
            onChange={(e) => setApiSeedCount(parseInt(e.target.value))}
            className="flex-1 h-1 bg-[var(--border)] rounded cursor-pointer accent-[var(--accent)]"
          />
          <span className="text-xs font-mono bg-[var(--accent-bg)] text-[var(--accent)] px-2 py-0.5 rounded-sm">
            {apiSeedCount} / 5
          </span>
        </div>
      </>
    )}

    <div className="flex items-center gap-2 pt-1">
      <span className="text-[9px] font-semibold text-[var(--text-muted)] uppercase tracking-widest">Fit Function</span>
      <div className="flex-1 border-t border-[var(--border)]" />
    </div>

    <div className="flex bg-[var(--surface-muted)] p-0.5 rounded-sm">
      {FIT_MODE_ORDER.map((id) => (
        <button
          key={id}
          onClick={() => setPaletteFitMode(id)}
          className={`flex-1 py-1.5 text-[9px] rounded-sm font-semibold tracking-widest uppercase transition-all ${
            paletteFitMode === id
              ? 'bg-[var(--surface)] text-[var(--accent)]'
              : 'text-[var(--text-muted)] hover:text-[var(--text)]'
          }`}
        >
          {FIT_MODES[id].label}
        </button>
      ))}
    </div>

    <p className="text-[10px] text-[var(--text-muted)] leading-relaxed">
      {FIT_MODE_DESCRIPTIONS[paletteFitMode]}
    </p>

    {paletteFitMode === 'poly' && (
      <div className="flex items-center gap-4">
        <label className="text-[10px] font-semibold text-[var(--text-secondary)] w-16 uppercase tracking-wider">Degree</label>
        <input
          type="range" min="1" max="6" step="1"
          value={degree}
          onChange={(e) => setDegree(parseInt(e.target.value))}
          className="flex-1 h-1 bg-[var(--border)] rounded cursor-pointer accent-[var(--accent)]"
        />
        <span className="text-xs font-mono bg-[var(--accent-bg)] text-[var(--accent)] px-2 py-0.5 rounded-sm">
          {degree}
        </span>
      </div>
    )}

    {paletteMethod !== 'api' && (
      <div className="flex items-center gap-4">
        <label className="text-[10px] font-semibold text-[var(--text-secondary)] w-20 uppercase tracking-wider">Colors</label>
        <input
          type="range" min="3" max="7" step="1"
          value={colorCount}
          onChange={(e) => setColorCount(parseInt(e.target.value))}
          className="flex-1 h-1 bg-[var(--border)] rounded cursor-pointer accent-[var(--accent)]"
        />
        <span className="text-xs font-mono bg-[var(--accent-bg)] text-[var(--accent)] px-2 py-0.5 rounded-sm">
          {colorCount}
        </span>
      </div>
    )}

    {paletteFitMode === 'cosine' && (
      <div className="flex items-center gap-3">
        <label className="text-[10px] font-semibold text-[var(--text-secondary)] w-20 uppercase tracking-wider">Lock freq</label>
        <Toggle on={lockFrequency} onToggle={() => setLockFrequency((v) => !v)} labelOn="Integer c" labelOff="Free float c" />
        <span className="text-[10px] text-[var(--text-muted)]">
          {lockFrequency ? 'Integer c (perfect loop)' : 'Free float c'}
        </span>
      </div>
    )}

    {(paletteFitMode === 'linear' || paletteFitMode === 'catmull') && paletteMethod !== 'api' && (
      <div className="flex items-center gap-3">
        <label className="text-[10px] font-semibold text-[var(--text-secondary)] w-20 uppercase tracking-wider">Weight dom.</label>
        <Toggle on={weightDominance} onToggle={() => setWeightDominance((v) => !v)} labelOn="t ∝ area" labelOff="Uniform t" />
        <span className="text-[10px] text-[var(--text-muted)]">
          {weightDominance ? 't ∝ area' : 'Uniform t'}
        </span>
      </div>
    )}

    <div className={`space-y-1 ${extractedColors.length === 0 ? 'hidden' : ''}`}>
      <div className="flex items-center justify-between">
        <h4 className="text-[9px] font-semibold text-[var(--text-muted)] uppercase tracking-widest">Extracted Points</h4>
        <button
          onClick={onShuffle}
          className="flex items-center gap-1 text-[9px] bg-[var(--text)] hover:bg-[var(--text-hover)] text-[var(--bg)] px-2 py-0.5 rounded-sm transition-colors tracking-wider uppercase font-semibold"
        >
          <Shuffle className="w-3 h-3" /> Shuffle
        </button>
      </div>
      <div className="overflow-hidden border border-[var(--border)] h-12">
        <canvas ref={paletteSwatchRef} width={500} height={48} className="w-full h-full" />
      </div>
      <h4 className="text-[9px] font-semibold text-[var(--text-muted)] uppercase tracking-widest pt-1">Fitted Gradient</h4>
      <div className="overflow-hidden border border-[var(--border)] h-12">
        <canvas ref={paletteGradientRef} width={500} height={48} className="w-full h-full" />
      </div>
    </div>
  </div>
);

export default PaletteModeSettings;
